version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: americor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres