client:
    resource:
        path: ../src/Client/Application/Controller/
        namespace: App\Client\Application\Controller
    type: attribute

credit:
    resource:
        path: ../src/Credit/Application/Controller/
        namespace: App\Credit\Application\Controller
    type: attribute